
# OSG
MACRO(OSG_USE_DIRECTORIES)
	INCLUDE_DIRECTORIES(${OSG_INCLUDE_DIR})
	INCLUDE_DIRECTORIES(${OPENTHREADS_INCLUDE_DIR})
	LINK_DIRECTORIES(${OSG_LIBRARY})
	LINK_DIRECTORIES(${OPENTHREADS_LIBRARY})
ENDMACRO(OSG_USE_DIRECTORIES)

MACRO(OSG_USE_MODULES TRGTNAME)
	SET(OSG_LIBS osgWidget osgDB osgUtil osg osgViewer osgGA osgText)
	FOREACH(LINKLIB ${OSG_LIBS}) 
		TARGET_LINK_LIBRARIES(${TRGTNAME} optimized ${LINKLIB} debug ${LINKLIB}d)
	ENDFOREACH(LINKLIB)
	TARGET_LINK_LIBRARIES(${TRGTNAME} optimized OpenThreads debug OpenThreadsd)
ENDMACRO(OSG_USE_MODULES TRGTNAME)
