

MACRO(CUSTOMIZED_TARGET_LINK_LIBRARIES TRGTNAME LINKLIBS PRE_FIX RELEASE_POSTFIX DEBUG_POSTFIX)
	FOREACH(LINKLIB ${LINKLIBS}) 
		TARGET_LINK_LIBRARIES(${TRGTNAME} optimized ${PRE_FIX}${LINKLIB}${RELEASE_POSTFIX} debug ${PRE_FIX}${LINKLIB}${DEBUG_POSTFIX})
	ENDFOREACH(LINKLIB)
ENDMACRO(CUSTOMIZED_TARGET_LINK_LIBRARIES)


MACRO(QT4_USE_MODULES TRGTNAME LINKLIB)
	TARGET_LINK_LIBRARIES(${TRGTNAME} optimized Qt${LINKLIB}4 debug Qt${LINKLIB}d4)
	message("${LINKLIB}")
ENDMACRO(QT4_USE_MODULES)


INCLUDE_DIRECTORIES(${QT_INCLUDE_DIR} 
	${QT_QTCORE_INCLUDE_DIR}
	${QT_QTGUI_INCLUDE_DIR}
	)
	
LINK_DIRECTORIES(${Qt_LIBv4_DIR})